### ISSUE TITLE
`cargo install mdbook-last-changed` doesn't work

### ISSUE THREAD

**Issue by m-cat** [badboy/mdbook-last-changed#1]
This looks like exactly what I need, but unfortunately the installation doesn't seem to work.

**Comment by badboy** [comment]
"doesn't work" is not a useful bug report. Tell people WHAT doesn't work.

Beyond that: This crate is not yet published (see https://crates.io/search?q=mdbook-last-changed), so yeah. That won't work because it can't find it. Use `cargo install --git https://github.com/badboy/mdbook-last-changed/` for the time being.

**Comment by m-cat** [comment]
Ha, that was silly of me. Yeah, I noticed it was not yet published, that's what I intended to alert you to.

**Comment by badboy** [comment]
[Published](https://crates.io/crates/mdbook-last-changed)

**Comment by m-cat** [comment]
Thank you! 🎉
